# Generated by Django 4.2.1 on 2023-06-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choice',
            field=models.CharField(choices=[('article', 'статья'), ('news', 'новость')], default='news', max_length=7),
        ),
    ]
